name: Combined Docker CI/CD build files

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    types: [opened, synchronize, reopened, closed]
jobs:
  # Build, lint and test our docker image for pull requests
  ci_build_and_test_job:
    if: (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      
    - name: Build the Docker image
      run: docker build . --file src/MovieCentral.Server/Dockerfile --tag moviecentral:latest

  # Build, lint, test and deploy docker image to DockerHub on closed PR or push to main branch
  cd_build_and_deploy_job:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
    
    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        
    - name: Build and Push Docker Image
      uses: docker/build-push-action@v3.0.0
      with:
        push: true
        pull: true
        tags: nudua/moviecentral:latest
        context: .
        file: src/MovieCentral.Server/Dockerfile
        

  
